apiVersion: v1
kind: Service
metadata:
  name: k8s-classtask
spec:
  selector:
    app: k8s-classtask
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  externalIPs:
    - 192.168.100.2
  type: LoadBalancer
