name: Kubernetes App 

on:
  push:
    branches: master


jobs:
  build-merge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.16
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.16

    - name: Run all
      run: make all
